#!/bin/bash
TEMP_BRANCH=temp/stabilize
git fetch origin master:$TEMP_BRANCH
if [ $? -eq 0 ]; then
	git fetch origin testing:testing && git fetch origin stable:stable \
	&& git push . $TEMP_BRANCH:stable
	git branch -d $TEMP_BRANCH
fi
