#!/bin/bash
TEMP_BRANCH=temp/stabilize_master
git checkout master && git fetch origin master:$TEMP_BRANCH && git checkout $TEMP_BRANCH && git fetch origin testing:testing && git fetch origin stable:stable \
&& git checkout master && git merge $TEMP_BRANCH \
&& git checkout testing && git merge master \
&& git checkout stable && git merge testing \
&& git branch -d $TEMP_BRANCH
